pages:
  stage: deploy
  script:
    # 1. ติดตั้งและเรียกใช้ NVM เพื่อลง Node.js ชั่วคราว
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - \. "$NVM_DIR/nvm.sh"
    - nvm install 20
    # 2. เริ่มขั้นตอนปกติ
    - npm install
    - npm run build
    - rm -rf public
    - cp -r dist public
  artifacts:
    paths:
      - public
  only:
    - main